require('core.plug')
require('core.binds')
require('core.colors')
require('core.options')

require('plugins.lsp')
require('plugins.cmp')
require('plugins.syntax')
require('plugins.filetree')
require('plugins.autoclosing')
